### ISSUE TITLE
Version 0.51+ fails to compile with MUSL

### ISSUE THREAD

**Issue by cetra3** [FillZpp/sys-info-rs#19]
When using musl as a target, I get the following error:

```
Compiling sys-info v0.5.2 (file:///home/rust/src/sys-info-rs)
error[E0432]: unresolved import `libc::sysctl`
  --> lib.rs:17:5
   |
17 | use libc::sysctl;
   |     ^^^^^^^^^^^^ no `sysctl` in the root. Did you mean to use `shmctl`?

error: aborting due to previous error(s)

error: Could not compile `sys-info`.

To learn more, run the command again with --verbose.
```

Version 0.50 works fine.

It appears that libc doesn't have a sysctl function for the musl target, but does for other targets.  

Looking at the code, this is only used with [mac osx in the boottime()](https://github.com/FillZpp/sys-info-rs/blob/master/lib.rs#L303) function.

**Comment by FillZpp** [comment]
Fixed in #20 , thanks @glebpom . 
Version 0.5.3 should be fine.
