### ISSUE TITLE
What unit is DiskInfo's `total` and `free` represented in?

### ISSUE THREAD

**Issue by JosephTLyons** [FillZpp/sys-info-rs#29]
What unit (byte, kilobyte, etc.) is returned when accessing

`sys_info::disk_info().unwrap().total`

or

`sys_info::disk_info().unwrap().free`

I can't seem to figure it out.

**Comment by FillZpp** [comment]
@JosephTLyons 
Both `sys_info::disk_info().unwrap().total` and `sys_info::disk_info().unwrap().free` return kilobyte(KB).
