### ISSUE TITLE
Seems to return invalid windows versions

### ISSUE THREAD

**Issue by mjarkk** [FillZpp/sys-info-rs#83]
When i use `os_release` on Windows 10 it returns `6.2.9200` but when i match this value to the windows version i get Windows 8.  
I'm using https://en.wikipedia.org/wiki/Windows_NT#Releases as reference here, am i doing something wrong here or is this incorrect behavior?  

This is what `winver` has to say:
![image](https://user-images.githubusercontent.com/15320763/104963869-ab34b480-59db-11eb-9c45-c8866179938e.png)

**Comment by davidkna** [comment]
This will only work if you add a manifest to you application and target windows 10 ([source](https://docs.microsoft.com/en-us/windows/win32/sysinfo/targeting-your-application-at-windows-8-1))

**Comment by mjarkk** [comment]
So unless i specifically target windows 10 i don't know i use windows 10?  
That kinds makes this function useless right?  
Maybe the minor version matches the build number but i doubt that.

**Comment by davidkna** [comment]
Well yes, but adding the manifest isn't that hard.

**Comment by mjarkk** [comment]
That's not my point here I said this function is useless if you already know you are on windows 10 because that's the only usable info I can use from this internal windows version.  
Better said you could also just remove this function because if you add a manifest for windows 10 you already know you are running windows 10.

**Comment by davidkna** [comment]
You can use a manifest to tell windows that you support windows 10 (and 8.1...), but that shouldn't cause lower versions to become unsupported. The manifest is just an opt-in that tells windows your application won't crash if it reveals it's running 8.1+.

**Comment by mjarkk** [comment]
Well oke in that case i'm doing something wrong :)
