### ISSUE TITLE
cargo build fails on ppc64le

### ISSUE THREAD

**Issue by seth-priya** [FillZpp/sys-info-rs#9]
Hi,

I am working on porting sys-info-rs on ppc64le and running into the following issue while building it

   Compiling sys-info v0.4.1 (file:///root/sys-info-rs)
error[E0308]: mismatched types
  --> lib.rs:81:60
   |
81 |             Ok(String::from_utf8_lossy(ffi::CStr::from_ptr(get_os_type()).to_bytes()).into_owned())
   |                                                            ^^^^^^^^^^^^^ expected u8, found i8
   |
   = note: expected type `*const u8`
              found type `*const i8`
   = help: here are some functions which might fulfill your needs:
           - .offset(...)
           - .wrapping_offset(...)

error[E0308]: mismatched types
   --> lib.rs:100:60
    |
100 |             Ok(String::from_utf8_lossy(ffi::CStr::from_ptr(get_os_release()).to_bytes())
    |                                                            ^^^^^^^^^^^^^^^^ expected u8, found i8
    |
    = note: expected type `*const u8`
               found type `*const i8`
    = help: here are some functions which might fulfill your needs:
            - .offset(...)
            - .wrapping_offset(...)

error: aborting due to 2 previous errors

error: Could not compile `sys-info`.

To learn more, run the command again with --verbose.

 Looks like an issue due to the difference in signedness between Power and Intel.

**Comment by seth-priya** [comment]
Raised a PR with changes to fix the above issue - please let me know if any additional validation is required. I have executed cargo build and cargo test on both platforms (x86_64) and ppc64le and they seem to succeed
root@4edc892eee06:~/sys-info-rs# rustc --version
rustc 1.21.0-nightly (13d94d5fa 2017-08-10)
root@4edc892eee06:~/sys-info-rs# gcc --versio
gcc (Ubuntu/IBM 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Additional logs:
root@4edc892eee06:~/sys-info-rs# cargo build
   Compiling gcc v0.3.51
   Compiling sys-info v0.4.1 (file:///root/sys-info-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 4.52 secs
root@4edc892eee06:~/sys-info-rs# cargo test
   Compiling sys-info v0.4.1 (file:///root/sys-info-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 1.22 secs
     Running target/debug/deps/sys_info-01931d9c27353fab

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests sys_info

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

**Comment by TheUberCatman** [comment]
I have the same error currently.

**Comment by FillZpp** [comment]
Thanks for feedback, haven't test it on ppc64le before.
I have merged this PR and updated sys-info to v0.5.0, it should be work.

**Comment by seth-priya** [comment]
Thanks @FillZpp !
